package com.sjm.financialapplication.model;
// Generated Jul 26, 2016 6:39:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountTransaction generated by hbm2java
 */
public class AccountTransaction  implements java.io.Serializable {


     private int transId;
     private Date transDate;
     private String category;
     private String description;
     private String transType;
     private BigDecimal amount;
     private BigDecimal curBalance;
     private Date entry;
     private Account account;

    public AccountTransaction() {
    }

	
    public AccountTransaction(Date transDate, String transType, BigDecimal amount, Account account) {
        this.transDate = transDate;
        this.transType = transType;
        this.amount = amount;
        this.account = account;
    }
    public AccountTransaction(Date transDate, String category, String description, String transType, BigDecimal amount, BigDecimal curBalance, Date entry, Account account) {
       this.transDate = transDate;
       this.category = category;
       this.description = description;
       this.transType = transType;
       this.amount = amount;
       this.curBalance = curBalance;
       this.entry = entry;
       this.account = account;
    }
   
    public int getTransId() {
        return this.transId;
    }
    
    public void setTransId(int transId) {
        this.transId = transId;
    }
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTransType() {
        return this.transType;
    }
    
    public void setTransType(String transType) {
        this.transType = transType;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getCurBalance() {
        return this.curBalance;
    }
    
    public void setCurBalance(BigDecimal curBalance) {
        this.curBalance = curBalance;
    }
    public Date getEntry() {
        return this.entry;
    }
    
    public void setEntry(Date entry) {
        this.entry = entry;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }




}


