package com.sjm.financialapplication.model;
// Generated Jul 26, 2016 6:39:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Accountowner generated by hbm2java
 */
public class Accountowner  implements java.io.Serializable {


     private String appUserId;
     private String firstName;
     private String lastName;
     private String gender;
     private String city;
     private String stateResidence;
     private String zip;
     private String street;
     private Set accounts = new HashSet(0);

    public Accountowner() {
    }

	
    public Accountowner(String appUserId, String firstName, String lastName, String gender) {
        this.appUserId = appUserId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
    }
    public Accountowner(String appUserId, String firstName, String lastName, String gender, String city, String stateResidence, String zip, String street, Set accounts) {
       this.appUserId = appUserId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.city = city;
       this.stateResidence = stateResidence;
       this.zip = zip;
       this.street = street;
       this.accounts = accounts;
    }
   
    public String getAppUserId() {
        return this.appUserId;
    }
    
    public void setAppUserId(String appUserId) {
        this.appUserId = appUserId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStateResidence() {
        return this.stateResidence;
    }
    
    public void setStateResidence(String stateResidence) {
        this.stateResidence = stateResidence;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


