package com.sjm.financialapplication.model;
// Generated Jul 26, 2016 6:39:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AppUser generated by hbm2java
 */
public class AppUser  implements java.io.Serializable {


     private String appUserId;
     private String password;
     private Date startDate;

    public AppUser() {
    }

    public AppUser(String appUserId, String password, Date startDate) {
       this.appUserId = appUserId;
       this.password = password;
       this.startDate = startDate;
    }
   
    public String getAppUserId() {
        return this.appUserId;
    }
    
    public void setAppUserId(String appUserId) {
        this.appUserId = appUserId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }




}


